### ISSUE TITLE
Not working with Java 7

### ISSUE THREAD

**Issue by TobiX** [bevuta/pepa#10]
The installation guide lists Java 7 as the minimum requirement, but on a Debian 8 (jessie) system, `lein uberjar` fails with

```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at clojure.main.<clinit>(main.java:20)
Caused by: java.lang.UnsupportedClassVersionError: org/postgresql/util/PGobject : Unsupported major.minor version 52.0, compiling:(pepa/db.clj:1:1)
        at clojure.lang.Compiler.load(Compiler.java:7441)
```

So it seems the PostgreSQL driver needs Java 8, which require Backports on a stable Debian system...

**Comment by the-kenny** [comment]
I'll check how much work supporting java7 would be. We'll also fix the documentation error soon.

**Comment by TobiX** [comment]
Using the correct version of the PostgreSQL JDBC driver¹ at least creates a jar...

¹ [org.postgresql/postgresql "42.0.0.jre7"]

**Comment by TobiX** [comment]
Not useful anymore :dagger:
