### ISSUE TITLE
java.lang.Error: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.

### ISSUE THREAD

**Issue by banrieen** [bevuta/pepa#13]
[root@izwz90ajic0vbw7o4pj6xyz pepa2]# java -jar pepa-0.1.0-SNAPSHOT-standalone.jar

15:46:06.747 INFO  [pepa.bus] Starting Bus
15:46:06.810 INFO  [pepa.db] Starting database
15:46:07.128 INFO  [pepa.web] Starting HTTP Server
15:46:07.128 INFO  [pepa.web] Started web server on http://localhost:8070/
15:46:07.204 INFO  [org.xnio] XNIO version 3.3.6.Final
15:46:07.227 INFO  [org.xnio.nio] XNIO NIO Implementation Version 3.3.6.Final
15:46:07.420 INFO  [org.projectodd.wunderboss.web.Web] Registered web context /
15:46:07.423 INFO  [pepa.processor.page-ocr] Starting page OCR processor
15:46:07.457 INFO  [pepa.processor.file-page-extractor] Starting file page extractor
15:46:07.484 INFO  [pepa.processor.page-renderer] Starting page renderer
Exception in thread "async-thread-macro-1" java.lang.Error: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:690)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:298)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:628)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at pepa.processor$next_item_STAR_.invokeStatic(processor.clj:14)
        at pepa.processor$next_item_STAR_.invoke(processor.clj:13)
        at pepa.processor$process_next.invokeStatic(processor.clj:21)
        at pepa.processor$process_next.invoke(processor.clj:19)
        at pepa.processor$start$fn__20979.invoke(processor.clj:35)
        at clojure.core.async$thread_call$fn__7338.invoke(async.clj:439)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
Caused by: com.mchange.v2.resourcepool.TimeoutException: A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@703c90bc -- timeout at awaitAvailable()
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1467)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
        ... 17 more
Exception in thread "async-thread-macro-3" java.lang.Error: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:690)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:298)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:628)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at pepa.processor$next_item_STAR_.invokeStatic(processor.clj:14)
        at pepa.processor$next_item_STAR_.invoke(processor.clj:13)
        at pepa.processor$process_next.invokeStatic(processor.clj:21)
        at pepa.processor$process_next.invoke(processor.clj:19)
        at pepa.processor$start$fn__20979.invoke(processor.clj:35)
        at clojure.core.async$thread_call$fn__7338.invoke(async.clj:439)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
Caused by: com.mchange.v2.resourcepool.TimeoutException: A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@703c90bc -- timeout at awaitAvailable()
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1467)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
        ... 17 more
Exception in thread "async-thread-macro-2" java.lang.Error: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1155)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: An attempt by a client to checkout a Connection has timed out.
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:118)
        at com.mchange.v2.sql.SqlUtils.toSQLException(SqlUtils.java:77)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:690)
        at com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource.getConnection(AbstractPoolBackedDataSource.java:140)
        at clojure.java.jdbc$get_connection.invokeStatic(jdbc.clj:298)
        at clojure.java.jdbc$get_connection.invoke(jdbc.clj:193)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:628)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at clojure.java.jdbc$db_transaction_STAR_.invokeStatic(jdbc.clj:598)
        at clojure.java.jdbc$db_transaction_STAR_.invoke(jdbc.clj:585)
        at pepa.processor$next_item_STAR_.invokeStatic(processor.clj:14)
        at pepa.processor$next_item_STAR_.invoke(processor.clj:13)
        at pepa.processor$process_next.invokeStatic(processor.clj:21)
        at pepa.processor$process_next.invoke(processor.clj:19)
        at pepa.processor$start$fn__20979.invoke(processor.clj:35)
        at clojure.core.async$thread_call$fn__7338.invoke(async.clj:439)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        ... 2 more
Caused by: com.mchange.v2.resourcepool.TimeoutException: A client timed out while waiting to acquire a resource from com.mchange.v2.resourcepool.BasicResourcePool@703c90bc -- timeout at awaitAvailable()
        at com.mchange.v2.resourcepool.BasicResourcePool.awaitAvailable(BasicResourcePool.java:1467)
        at com.mchange.v2.resourcepool.BasicResourcePool.prelimCheckoutResource(BasicResourcePool.java:644)
        at com.mchange.v2.resourcepool.BasicResourcePool.checkoutResource(BasicResourcePool.java:554)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutAndMarkConnectionInUse(C3P0PooledConnectionPool.java:758)
        at com.mchange.v2.c3p0.impl.C3P0PooledConnectionPool.checkoutPooledConnection(C3P0PooledConnectionPool.java:685)
        ... 17 more

**Comment by banrieen** [comment]
The system security role caused!
