### ISSUE TITLE
Stacktrace

### ISSUE THREAD

**Issue by BernhardBln** [bevuta/pepa#5]
Hey guys,

wanted to try out pepa.

I believe I installed all the required prerequisites (basically by copy-pasting your _apt-get install_ line from the Readme), still I'm getting this stacktrace when I upload a document. The document is not visible in the UI after this.

Any ideas? Must there something (Poppler?) be configured or anything?

I'm using Google Chrome on a Linux Mint system, Leiningen 2.5.1 on Java 1.8.0_66 Java HotSpot(TM) 64-Bit Server VM.

```
22:57:56.215 INFO  [FilePageExtractor] Start processing file 3 (10498 bytes, origin: web)
22:57:56.289 INFO  [FilePageExtractor] Processing page 0
22:57:56.353 ERROR [FilePageExtractor] Exception in `process-item'.
java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170) ~[na:1.8.0_66]
    at java.io.BufferedInputStream.read(BufferedInputStream.java:336) ~[na:1.8.0_66]
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[na:1.8.0_66]
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[na:1.8.0_66]
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[na:1.8.0_66]
    at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[na:1.8.0_66]
    at java.io.BufferedReader.fill(BufferedReader.java:161) ~[na:1.8.0_66]
    at java.io.BufferedReader.read(BufferedReader.java:182) ~[na:1.8.0_66]
    at clojure.core$slurp.doInvoke(core.clj:6650) ~[pepa-0.1.0-SNAPSHOT-standalone.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:410) [pepa-0.1.0-SNAPSHOT-standalone.jar:na]
    at pepa.pdf.PopplerReader.extract_page_text(pdf.clj:75) ~[na:na]
    at pepa.processor.file_page_extractor$extract_pages.invoke(file_page_extractor.clj:15) ~[na:na]
    at pepa.processor.file_page_extractor.FilePageExtractor$fn__18280$fn__18281.invoke(file_page_extractor.clj:34) ~[na:na]
    at pepa.processor.file_page_extractor.FilePageExtractor$fn__18280.invoke(file_page_extractor.clj:33) [na:na]
    at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:595) [na:na]
    at clojure.lang.RestFn.invoke(RestFn.java:521) [pepa-0.1.0-SNAPSHOT-standalone.jar:na]
    at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:611) [na:na]
    at clojure.lang.RestFn.invoke(RestFn.java:425) [pepa-0.1.0-SNAPSHOT-standalone.jar:na]
    at pepa.processor.file_page_extractor.FilePageExtractor.process_item(file_page_extractor.clj:32) [na:na]
    at pepa.processor$process_next$fn__18242.invoke(processor.clj:22) [na:na]
    at pepa.processor$process_next.invoke(processor.clj:21) [na:na]
    at pepa.processor$start$fn__18246.invoke(processor.clj:34) [na:na]
    at clojure.core.async$thread_call$fn__5893.invoke(async.clj:405) [na:na]
    at clojure.lang.AFn.run(AFn.java:22) [pepa-0.1.0-SNAPSHOT-standalone.jar:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
java.io.IOException: Stream closed
    at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:336)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:161)
    at java.io.BufferedReader.read(BufferedReader.java:182)
    at clojure.core$slurp.doInvoke(core.clj:6650)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at pepa.pdf.PopplerReader.extract_page_text(pdf.clj:75)
    at pepa.processor.file_page_extractor$extract_pages.invoke(file_page_extractor.clj:15)
    at pepa.processor.file_page_extractor.FilePageExtractor$fn__18280$fn__18281.invoke(file_page_extractor.clj:34)
    at pepa.processor.file_page_extractor.FilePageExtractor$fn__18280.invoke(file_page_extractor.clj:33)
    at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:595)
    at clojure.lang.RestFn.invoke(RestFn.java:521)
    at clojure.java.jdbc$db_transaction_STAR_.doInvoke(jdbc.clj:611)
    at clojure.lang.RestFn.invoke(RestFn.java:425)
    at pepa.processor.file_page_extractor.FilePageExtractor.process_item(file_page_extractor.clj:32)
    at pepa.processor$process_next$fn__18242.invoke(processor.clj:22)
    at pepa.processor$process_next.invoke(processor.clj:21)
    at pepa.processor$start$fn__18246.invoke(processor.clj:34)
    at clojure.core.async$thread_call$fn__5893.invoke(async.clj:405)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
22:57:56.368 WARN  [FilePageExtractor] Failed to render file 3
22:57:56.394 INFO  [FilePageExtractor] Finished processing of file 3
```

**Comment by the-kenny** [comment]
Sorry for the issue! This is actually a regression I encountered before.

It's a race condition in our subprocess handling. I've got a fix somewhere
and I'll port or to master in the next hour or so.

**Comment by the-kenny** [comment]
I just merged a branch containing a completely revamped Inbox. This merge was overdue, and your bug report finally made me merge it (as that branch contains a fix). 

Enjoy! (and please re-open if the bug still exists)

**Comment by the-kenny** [comment]
@DerGuteMoritz just suggested another thing: As this is a rather big merge, please run `lein clean` and rebuild Clojurescript after pulling in the new master. Just to avoid any trouble.

**Comment by BernhardBln** [comment]
Will try tonight. Thanks for the quick reply and the info :)
