### ISSUE TITLE
Problem with pdfunite

### ISSUE THREAD

**Issue by BernhardBln** [bevuta/pepa#6]
Hey guys,

I can now upload and view documents, but when I try to download them, I'm getting this stacktrace:

```
clojure.lang.ExceptionInfo: pdfunit didn't terminate correctly {:exit-code 99, :args ("/tmp/pdfseparate-2586469553236351662.pdf" "/tmp/pdfunite-123464094108447981.pdf"), :pages (#object[java.io.File 0x61dc0674 "/tmp/pdfseparate-2586469553236351662.pdf"])}
    at clojure.core$ex_info.invoke(core.clj:4591)
    at pepa.pdf$merge_pages.invoke(pdf.clj:177)
    at pepa.model$document_pdf.invoke(model.clj:480)
    at pepa.web.handlers$document_download$fn__15620$fn__15623.invoke(handlers.clj:219)
    at liberator.core$decide.invoke(core.clj:80)
[...]
```

This is what I see in the repl:

```
21:13:37.990 INFO  [Database] Generating PDF for 5
pdfunite version 0.24.5
Copyright 2005-2013 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
Usage: pdfunite [options] <PDF-sourcefile-1>..<PDF-sourcefile-n> <PDF-destfile>
  -v             : print copyright and version info
  -h             : print usage information
  -help          : print usage information
  --help         : print usage information
  -?             : print usage information
```

Feels like the process is not correctly invoked. I hope the pdfunite version I have is recent enough?

And why is it actually merging pdfs? I thought the file I uploaded would be stored as it is, and then downloaded as it is?

**Comment by the-kenny** [comment]
I'm not sure what's the issue here. I'm currently on vacation until Tuesday
and on limited data volume, but I'll take a look as soon as possible.

Pdfunite is only needed for documents consisting of multiple files, but we
threw away the second choice path (handling the optimized case) for the
sake of simplicity.

I wonder why it didn't work, as the arguments array clearly contains two
files. Might be another regression :/

**Comment by BernhardBln** [comment]
Sure, it's not urgent, thanks for the quick reply :)

That the arguments array contains two files, puzzles me in turn - the file in question is one PDF with exactly one page...

**Comment by the-kenny** [comment]
It's input and output, so that's expected. We should add that sort circuit
for simple files again, as it's a pretty common case.
